import { NextResponse } from "next/server";

export const courses = [
  {
    id: 1,
    category: "Course",
    title: "Service Design Essentials",
    description: "Learn essential service design concepts and methods.",
    price: 3559,
    currency: "THB",
    thumbnail: "https://picsum.photos/seed/service-design/600/400",
    videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    instructor: "Jane Doe",
    rating: 4.7,
    students: 1280,
    language: "English",
    durationHours: 6,
    modules: [
      {
        id: 1,
        title: "Introduction",
        lessons: [
          "Welcome to the Course",
          "Course Overview",
          "What is Service Design?",
        ],
      },
      {
        id: 2,
        title: "Service Design Theories",
        lessons: [
          "Core Principles",
          "System Thinking",
          "Human-Centered Approach",
        ],
      },
    ],
  },
  {
    id: 2,
    category: "Course",
    title: "UI/UX Design Fundamentals",
    description: "Principles of user interface and user experience design.",
    price: 4200,
    currency: "THB",
    thumbnail: "https://picsum.photos/seed/uiux/600/400",
    videoUrl: "https://www.youtube.com/embed/9No-FiEInLA",
    instructor: "John Smith",
    rating: 4.5,
    students: 980,
    language: "Thai",
    durationHours: 8,
    modules: [
      {
        id: 1,
        title: "Introduction to UX",
        lessons: ["What is UX?", "Why UX matters"],
      },
      {
        id: 2,
        title: "UI Basics",
        lessons: ["Typography", "Color Theory", "Layout"],
      },
    ],
  },
  {
    id: 3,
    category: "Workshop",
    title: "Agile for Beginners",
    description: "Hands-on workshop to learn Agile methodology.",
    price: 2500,
    currency: "THB",
    thumbnail: "https://picsum.photos/seed/agile/600/400",
    videoUrl: "https://www.youtube.com/embed/ysz5S6PUM-U",
    instructor: "Alice Johnson",
    rating: 4.6,
    students: 600,
    language: "English",
    durationHours: 4,
    modules: [
      {
        id: 1,
        title: "Agile Basics",
        lessons: ["What is Agile?", "Agile vs. Waterfall"],
      },
    ],
  },
  {
    id: 4,
    category: "Course",
    title: "Fullstack Web Development",
    description: "Become a fullstack developer with React, Node.js, and DBs.",
    price: 6900,
    currency: "THB",
    thumbnail: "https://picsum.photos/seed/fullstack/600/400",
    videoUrl: "https://www.youtube.com/embed/rfscVS0vtbw",
    instructor: "Michael Lee",
    rating: 4.8,
    students: 2100,
    language: "English",
    durationHours: 12,
    modules: [
      {
        id: 1,
        title: "Frontend Basics",
        lessons: ["HTML", "CSS", "JavaScript"],
      },
      {
        id: 2,
        title: "Backend Basics",
        lessons: ["Node.js", "Express", "Database"],
      },
    ],
  },
  {
    id: 5,
    category: "Course",
    title: "Data Science with Python",
    description: "Learn data science, pandas, numpy, and visualization.",
    price: 5000,
    currency: "THB",
    thumbnail: "https://picsum.photos/seed/datasci/600/400",
    videoUrl: "https://www.youtube.com/embed/kqtD5dpn9C8",
    instructor: "Sarah Wong",
    rating: 4.9,
    students: 3200,
    language: "English",
    durationHours: 10,
    modules: [
      {
        id: 1,
        title: "Python Basics",
        lessons: ["Syntax", "Data Types", "Functions"],
      },
      {
        id: 2,
        title: "Data Analysis",
        lessons: ["Pandas", "Numpy", "Matplotlib"],
      },
    ],
  },
  {
    id: 6,
    category: "Bootcamp",
    title: "Digital Marketing Mastery",
    description: "Grow your business with digital marketing strategies.",
    price: 2999,
    currency: "THB",
    thumbnail: "https://picsum.photos/seed/marketing/600/400",
    videoUrl: "https://www.youtube.com/embed/3fumBcKC6RE",
    instructor: "David Kim",
    rating: 4.4,
    students: 1100,
    language: "Thai",
    durationHours: 5,
    modules: [
      {
        id: 1,
        title: "Marketing Basics",
        lessons: ["SEO", "Social Media", "Email Marketing"],
      },
    ],
  },
  {
    id: 7,
    category: "Course",
    title: "Mobile App Development",
    description: "Build mobile apps using Flutter and React Native.",
    price: 4500,
    currency: "THB",
    thumbnail: "https://picsum.photos/seed/mobile/600/400",
    videoUrl: "https://www.youtube.com/embed/f02mOEt11OQ",
    instructor: "Emily Davis",
    rating: 4.6,
    students: 900,
    language: "English",
    durationHours: 9,
    modules: [
      {
        id: 1,
        title: "Introduction to Mobile",
        lessons: ["Flutter Setup", "Hello World App"],
      },
    ],
  },
  {
    id: 8,
    category: "Course",
    title: "Cloud Computing Basics",
    description: "Get started with AWS, Azure, and GCP.",
    price: 4000,
    currency: "THB",
    thumbnail: "https://picsum.photos/seed/cloud/600/400",
    videoUrl: "https://www.youtube.com/embed/2LaAJq1lB1Q",
    instructor: "Robert Wilson",
    rating: 4.3,
    students: 750,
    language: "English",
    durationHours: 7,
    modules: [
      {
        id: 1,
        title: "Cloud Intro",
        lessons: ["What is Cloud?", "AWS Basics"],
      },
    ],
  },
  {
    id: 9,
    category: "Course",
    title: "Machine Learning Essentials",
    description: "Understand ML algorithms and build simple models.",
    price: 5500,
    currency: "THB",
    thumbnail: "https://picsum.photos/seed/ml/600/400",
    videoUrl: "https://www.youtube.com/embed/GwIo3gDZCVQ",
    instructor: "Sophia Brown",
    rating: 4.8,
    students: 1800,
    language: "English",
    durationHours: 11,
    modules: [
      {
        id: 1,
        title: "ML Basics",
        lessons: ["Supervised vs Unsupervised", "Linear Regression"],
      },
    ],
  },
  {
    id: 10,
    category: "Course",
    title: "Cybersecurity 101",
    description: "Learn the fundamentals of cybersecurity.",
    price: 3800,
    currency: "THB",
    thumbnail: "https://picsum.photos/seed/cyber/600/400",
    videoUrl: "https://www.youtube.com/embed/inWWhr5tnEA",
    instructor: "Daniel White",
    rating: 4.5,
    students: 670,
    language: "English",
    durationHours: 6,
    modules: [
      {
        id: 1,
        title: "Security Basics",
        lessons: ["Threats", "Vulnerabilities", "Encryption"],
      },
    ],
  },
  {
    id: 11,
    category: "Course",
    title: "Entrepreneurship for Beginners",
    description: "Turn your ideas into real businesses.",
    price: 2600,
    currency: "THB",
    thumbnail: "https://picsum.photos/seed/startup/600/400",
    videoUrl: "https://www.youtube.com/embed/IUN664s7N-c",
    instructor: "Karen Green",
    rating: 4.2,
    students: 500,
    language: "Thai",
    durationHours: 5,
    modules: [
      {
        id: 1,
        title: "Startup Basics",
        lessons: ["Idea Validation", "Business Model Canvas"],
      },
    ],
  },
  {
    id: 12,
    category: "Workshop",
    title: "Creative Problem Solving",
    description: "Develop creativity and problem-solving mindset.",
    price: 3100,
    currency: "THB",
    thumbnail: "https://picsum.photos/seed/creativity/600/400",
    videoUrl: "https://www.youtube.com/embed/1Y77dG4cU1w",
    instructor: "Paul Anderson",
    rating: 4.6,
    students: 820,
    language: "English",
    durationHours: 6,
    modules: [
      {
        id: 1,
        title: "Creativity Basics",
        lessons: ["Brainstorming", "Mind Mapping"],
      },
    ],
  },
];

// GET /api/courses
export async function GET() {
  return NextResponse.json(courses, { status: 200 });
}
