import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";


import { createSupabaseServerClient } from "@/lib/createSupabaseServerClient";
import Navbar from "@/components/ui/navbar";
import Navbar_test from "@/components/ui/Navbar_test";
import NonuserNav from "@/components/ui/navbar/NonuserNav";
import UserNav from "@/components/ui/navbar/UserNav";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const supabase = createSupabaseServerClient();
  const { data: { session } } = await supabase.auth.getSession();

  let userProfile = null;

  if(session){
    const { data: profiles } = await supabase
    .from('profiles')
    .select('*')
    .eq('id', session.user.id)
    .single();

    userProfile = profiles;
  }

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <UserNav session={session} userProfile={userProfile} />

        {children}
      </body>
    </html>
  );
}

//<Navbar_test session={session} userProfile={userProfile} />
