import type { Metadata } from "next";
import "./globals.css";


import { createSupabaseServerClient } from "@/lib/createSupabaseServerClient";
import HeaderNav from "@/components/ui/navbar/HeaderNav";
// import UserNav from "@/components/ui/navbar/UserNav";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const supabase = await createSupabaseServerClient();
  const { data: { session } } = await supabase.auth.getSession();

  // let userProfile = null;

  if(session){
    // const { data: profiles } = await supabase
    // .from('profiles')
    // .select('*')
    // .eq('id', session.user.id)
    // .single();

    // userProfile = profiles;
  }

  return (
    <html lang="en">
      <body>
        <HeaderNav />
        {children}
      </body>
    </html>
  );
}

//<Navbar_test session={session} userProfile={userProfile} />
//<HeaderNav session={session} userProfile={userProfile} />

